export const learningData = [
  {
    roleId: "1",
    roleCategory: "App Roles",
    courseName: "AWS Devops Expert-Apps",
    proficiency: "Expert",
    courseDuration: "70+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B, d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "2",
    roleCategory: "App Roles",
    courseName: "AWS Solution Architect-Apps",
    proficiency: "Expert",
    courseDuration: "70+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B, e",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "3",
    roleCategory: "App Roles",
    courseName: "Cloud Full Stack Developer Apps (AWS)",
    proficiency: "Intermediate",
    courseDuration: "70+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B, c",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "4",
    roleCategory: "App Roles",
    courseName: "Developer Apps (AWS)",
    proficiency: "Beginner",
    courseDuration: "70+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "5",
    roleCategory: "Infra Roles",
    courseName: "AWS Cloud Engineer",
    proficiency: "Beginner",
    courseDuration: "50+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "6",
    roleCategory: "Infra Roles",
    courseName: "AWS Cloud Architect",
    proficiency: "Intermediate",
    courseDuration: "100+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,e",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "7",
    roleCategory: "Infra Roles",
    courseName: "AWS Devops Analyst",
    proficiency: "Intermediate",
    courseDuration: "90+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "8",
    roleCategory: "Infra Roles",
    courseName: "AWS Cloud SysOps Lead",
    proficiency: "Intermediate",
    courseDuration: "60+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,e",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "9",
    roleCategory: "Infra Roles",
    courseName: "AWS Solution Architect - Infra",
    proficiency: "Expert",
    courseDuration: "60+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,e",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "10",
    roleCategory: "Infra Roles",
    courseName: "AWS Devops Expert",
    proficiency: "Expert",
    courseDuration: "80+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,e",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "11",
    roleCategory: "Data Roles",
    courseName: "Cloud Data Scientist/ Expert - Apps (AWS)",
    proficiency: "Expert",
    courseDuration: "90+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A11, B,d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "12",
    roleCategory: "Data Roles",
    courseName: "AWS Data Architect Solution",
    proficiency: "Expert",
    courseDuration: "90+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A11, B,d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "13",
    roleCategory: "Data Roles",
    courseName: "Senior Data Engineer / Data Engineering Lead",
    proficiency: "Intermediate",
    courseDuration: "90+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "Abc, B,d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQLRESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
  {
    roleId: "14",
    roleCategory: "Data Roles",
    courseName: "Data Engineeer",
    proficiency: "Beginner",
    courseDuration: "70+ hours",
    experience: [
      "Trained in these skills",
      "Conceptual knowledge across all",
      "0-2 years hands-on experience",
    ],
    employeeGrade: "A, B,d",
    professionalCertification: "AZ 900 - Azure Foundation",
    internalCertification: "Not aplicable",
    mandatorySkills: [
      "Programming Languages - e.g. C#, .net, .Net Core etc.",
      "JavaScript-Frameworks - e.g. Angular,React etc.",
      "Database Knowledge - e.g. SQL/NoSQL RESTAPI",
      "Cloud Computing with the knowledge of any Public Cloud - e.e. Azure/AWS/Google",
      "Should be certified on Professional Certificate",
    ],
    goodToHaveSkills: [
      "Introduction to Cloud Migrations - Methodologies and tools",
      "TDD",
      "Microservices fundamentals",
      "Development Tools and IDE",
      "Knowledge of DevOps Tools",
      "Strong understanding of Agile development",
      "Understanding of software testing and optimization methodologies",
      "Creating rich documentaion for software solutions",
      "Should be certified with internal Certificates if any",
    ],
  },
];
